### Notebook 2 : Polynomial regression single feature

##### Import libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##### Load the data set

In [3]:
df = pd.read_csv('capstone.csv')

##### Extract inputs and targets

In [4]:

X = df['Attendance'].values.reshape(-1, 1)
y = df['CapstoneScore'].values

##### Scale X values

In [5]:
X_mean = np.mean(X)
X_std = np.std(X)
X_scaled = (X - X_mean) / X_std

##### Confirm the shapes

In [7]:
print(f"X_scaled shape: {X_scaled.shape}")
print(f"y shape: {y.shape}")

X_scaled shape: (150, 1)
y shape: (150,)


##### Create Polynomial Features

* Takes a (m, 1) input array X and returns a (m, degree+1) feature matrix with columns [1, x, x^2, ..., x^degree]

In [8]:
def create_polynomial_features(X, degree):

    m = X.shape[0]
    X_poly = np.ones((m, degree + 1))  # First column = 1 for β₀ (intercept)
    for d in range(1, degree + 1):
        X_poly[:, d] = X[:, 0] ** d
    return X_poly


* Testing with dummy values

In [9]:
X_poly_2 = create_polynomial_features(X_scaled, degree=2)
print(X_poly_2[:5])

[[ 1.          0.1817678   0.03303953]
 [ 1.         -0.09105992  0.00829191]
 [ 1.          1.65151709  2.72750871]
 [ 1.         -0.29348048  0.08613079]
 [ 1.          0.4721973   0.22297029]]


##### Implement fit polynomial